Document: tpmac
Title: Debian tpmac Manual
Author: <insert document author here>
Abstract: This manual describes what tpmac is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tpmac/tpmac.sgml.gz

Format: postscript
Files: /usr/share/doc/tpmac/tpmac.ps.gz

Format: text
Files: /usr/share/doc/tpmac/tpmac.text.gz

Format: HTML
Index: /usr/share/doc/tpmac/html/index.html
Files: /usr/share/doc/tpmac/html/*.html
